project:
  type: book
  output-dir: docs

book:
  title: "COMP/STAT112 Notebook"
  author: "Huthiafa Mohammad"
  date: "09/"
  reader-mode: true
  
  chapters:
    - index.qmd
    
    - part: Homework/homework_1.qmd
      chapters: 
        - aria-label: homework_1.qmd


    - part: activities/README.qmd
      chapters: 
      - activities/activity-01.qmd
      - activities/activity-02.qmd
      - activities/activity-03.qmd
    
    - part: notes/README.qmd
      chapters: 
      - notes/note-01.qmd
      - notes/note-02.qmd

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 1
    embed-resources: true
    code-copy: true
    code-line-numbers: true
    code-tools: true

execute:
  cache: true
  freeze: auto
